generatorName: python
inputSpec: /local/kestra-ee.yml
outputDir: /local/python-sdk

globalProperties:
  apiTests: false
  modelTests: false

additionalProperties:
  packageName: kestra_api_client
  projectName: kestra_api
  disallowAdditionalPropertiesIfNotPresent: false
